"""
ST-LMS v3 - Structural RAG (The Librarian)
Reads Truth Layer JSON files and provides efficient query capabilities.
NO Vector DB, NO LLM, NO SQLite - Pure Python with Binary Search.
"""
import json
import bisect
from typing import List, Optional, Dict, Any, Literal
from datetime import datetime
from pathlib import Path

import sys
sys.path.insert(0, '/workspace')

from pydantic import BaseModel, Field


class FactCard(BaseModel):
    """
    Standard response format for all RAG queries.
    Never returns raw objects - always wrapped in FactCard.
    """
    source: Literal["LineRAG", "WaveRAG", "PointRAG"] = Field(..., description="Source of the fact")
    object_id: str = Field(..., description="ID of the referenced object (line_id, wave_id, or point_id)")
    fact: str = Field(..., description="Human-readable fact summary generated by pure Python logic")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score based on strength/duration")
    references: List[str] = Field(default_factory=list, description="Related point_ids or line_ids")
    time_id: str = Field(..., description="Latest Time ID associated with this fact")
    
    class Config:
        json_schema_extra = {
            "example": {
                "source": "LineRAG",
                "object_id": "L2607081921-SUP-001",
                "fact": "Strong Support, retested 16 times, slope positive",
                "confidence": 0.94,
                "references": ["P2607081921", "P2607081936"],
                "time_id": "P2607081936"
            }
        }


class StructuralRAG:
    """
    The Librarian - Indexes and queries Truth Layer data.
    Uses binary search (bisect) for O(log n) price lookups.
    """
    
    def __init__(self, lines_path: str = "/workspace/truth_layer/storage/lines.json",
                 waves_path: str = "/workspace/truth_layer/storage/waves.json"):
        """
        Initialize RAG by loading JSON files and building indexes.
        
        Args:
            lines_path: Path to lines.json
            waves_path: Path to waves.json
        """
        self.lines_path = Path(lines_path)
        self.waves_path = Path(waves_path)
        
        # Raw data
        self.lines: List[Dict[str, Any]] = []
        self.waves: List[Dict[str, Any]] = []
        
        # Indexes for binary search
        self.support_lines_sorted_by_price: List[Dict[str, Any]] = []
        self.resistance_lines_sorted_by_price: List[Dict[str, Any]] = []
        self.support_prices: List[float] = []
        self.resistance_prices: List[float] = []
        self.waves_by_time: Dict[str, Dict[str, Any]] = {}
        
        # Load and build indexes
        self._load_data()
        self._build_indexes()
    
    def _load_data(self) -> None:
        """Load JSON files from Data Lake."""
        if self.lines_path.exists():
            with open(self.lines_path, 'r') as f:
                self.lines = json.load(f)
        
        if self.waves_path.exists():
            with open(self.waves_path, 'r') as f:
                self.waves = json.load(f)
    
    def _build_indexes(self) -> None:
        """
        Build sorted indexes for binary search.
        Separates SUPPORT and RESISTANCE lines, sorts by price.
        """
        self.support_lines_sorted_by_price = []
        self.resistance_lines_sorted_by_price = []
        self.support_prices = []
        self.resistance_prices = []
        self.waves_by_time = {}
        
        # Index lines by type and sort by price
        for line in self.lines:
            if line.get("type") == "SUPPORT":
                self.support_lines_sorted_by_price.append(line)
            elif line.get("type") == "RESISTANCE":
                self.resistance_lines_sorted_by_price.append(line)
        
        # Sort by current_price
        self.support_lines_sorted_by_price.sort(key=lambda x: x["current_price"])
        self.resistance_lines_sorted_by_price.sort(key=lambda x: x["current_price"])
        
        # Extract price lists for binary search
        self.support_prices = [line["current_price"] for line in self.support_lines_sorted_by_price]
        self.resistance_prices = [line["current_price"] for line in self.resistance_lines_sorted_by_price]
        
        # Index waves by time_id (from first member's line_id timestamp)
        for wave in self.waves:
            # Extract time from wave_id (format: W2607081921-001)
            wave_id = wave.get("wave_id", "")
            if wave_id.startswith("W") and "-" in wave_id:
                time_part = wave_id[1:].split("-")[0]  # Extract 2607081921
                full_time_id = f"P{time_part}"  # Convert back to point format
                self.waves_by_time[full_time_id] = wave
    
    def _find_nearest_index(self, sorted_prices: List[float], target_price: float) -> int:
        """
        Find index of nearest price using binary search.
        Returns -1 if list is empty.
        """
        if not sorted_prices:
            return -1
        
        # bisect_left finds insertion point to maintain sorted order
        idx = bisect.bisect_left(sorted_prices, target_price)
        
        # Check neighbors to find closest
        if idx == 0:
            return 0
        elif idx >= len(sorted_prices):
            return len(sorted_prices) - 1
        else:
            # Compare distances
            left_dist = abs(sorted_prices[idx - 1] - target_price)
            right_dist = abs(sorted_prices[idx] - target_price)
            return idx - 1 if left_dist <= right_dist else idx
    
    def _calculate_confidence(self, line: Dict[str, Any]) -> float:
        """
        Calculate confidence score based on line strength and version history.
        Pure Python logic - no ML/LLM.
        
        Factors:
        - strength: Number of confirmations (more = higher confidence)
        - versions: Number of price updates (shows active monitoring)
        - duration: Time span from first to last version
        """
        strength = line.get("strength", 0)
        versions = line.get("versions", [])
        
        # Base confidence from strength (cap at 0.7 for strength alone)
        strength_score = min(strength / 20.0, 0.7)  # 20+ strength = max 0.7
        
        # Version activity bonus (up to 0.2)
        version_count = len(versions)
        version_score = min(version_count / 10.0, 0.2)  # 10+ versions = max 0.2
        
        # Duration bonus (up to 0.1)
        if len(versions) >= 2:
            try:
                first_time = datetime.fromisoformat(versions[0]["time_wib"])
                last_time = datetime.fromisoformat(versions[-1]["time_wib"])
                duration_minutes = (last_time - first_time).total_seconds() / 60
                duration_score = min(duration_minutes / 60.0, 0.1)  # 60+ min = max 0.1
            except:
                duration_score = 0.0
        else:
            duration_score = 0.0
        
        confidence = strength_score + version_score + duration_score
        return min(max(confidence, 0.0), 1.0)  # Clamp to [0, 1]
    
    def _generate_fact_string(self, line: Dict[str, Any], line_type: str) -> str:
        """
        Generate human-readable fact string using pure Python logic.
        No LLM summarization.
        """
        strength = line.get("strength", 0)
        versions = line.get("versions", [])
        current_price = line.get("current_price", 0)
        
        # Determine strength descriptor
        if strength >= 15:
            strength_desc = "Very Strong"
        elif strength >= 10:
            strength_desc = "Strong"
        elif strength >= 5:
            strength_desc = "Moderate"
        else:
            strength_desc = "Weak"
        
        # Determine slope direction
        slope_desc = "flat"
        if len(versions) >= 2:
            first_price = versions[0]["price"]
            last_price = versions[-1]["price"]
            if last_price > first_price:
                slope_desc = "positive"
            elif last_price < first_price:
                slope_desc = "negative"
        
        # Count retests (number of MOVE events)
        retest_count = sum(1 for v in versions if v.get("event") == "MOVE")
        
        level_type = "Support" if line_type == "SUPPORT" else "Resistance"
        
        fact_parts = [
            f"{strength_desc} {level_type}",
            f"at {current_price:.2f}",
        ]
        
        if retest_count > 0:
            fact_parts.append(f"retested {retest_count} times")
        
        fact_parts.append(f"slope {slope_desc}")
        
        return ", ".join(fact_parts)
    
    def find_nearest_support(self, current_price: float) -> Optional[FactCard]:
        """
        Find nearest support level below or at current price using binary search.
        
        Args:
            current_price: Current market price
            
        Returns:
            FactCard with support info, or None if no support found
        """
        if not self.support_prices:
            return None
        
        # Find nearest support (should be at or below current price)
        idx = bisect.bisect_right(self.support_prices, current_price) - 1
        
        if idx < 0:
            # No support below current price
            return None
        
        line = self.support_lines_sorted_by_price[idx]
        
        return self._create_line_fact_card(line, "LineRAG")
    
    def find_nearest_resistance(self, current_price: float) -> Optional[FactCard]:
        """
        Find nearest resistance level above or at current price using binary search.
        
        Args:
            current_price: Current market price
            
        Returns:
            FactCard with resistance info, or None if no resistance found
        """
        if not self.resistance_prices:
            return None
        
        # Find nearest resistance (should be at or above current price)
        idx = bisect.bisect_left(self.resistance_prices, current_price)
        
        if idx >= len(self.resistance_prices):
            # No resistance above current price
            return None
        
        line = self.resistance_lines_sorted_by_price[idx]
        
        return self._create_line_fact_card(line, "LineRAG")
    
    def _create_line_fact_card(self, line: Dict[str, Any], source: Literal["LineRAG"]) -> FactCard:
        """
        Create a FactCard from a line object.
        """
        line_id = line.get("line_id", "UNKNOWN")
        line_type = line.get("type", "SUPPORT")
        versions = line.get("versions", [])
        members = line.get("members", [])
        
        # Get latest time_id from last version
        time_id = versions[-1]["point_id"] if versions else "UNKNOWN"
        
        fact = self._generate_fact_string(line, line_type)
        confidence = self._calculate_confidence(line)
        
        # References: first and last point_ids
        references = []
        if versions:
            references.append(versions[0]["point_id"])
            if len(versions) > 1:
                references.append(versions[-1]["point_id"])
        
        return FactCard(
            source=source,
            object_id=line_id,
            fact=fact,
            confidence=round(confidence, 2),
            references=references,
            time_id=time_id
        )
    
    def get_wave_context(self, current_time_id: str) -> Optional[FactCard]:
        """
        Get active wave context for a given time.
        
        Args:
            current_time_id: Time ID to look up (e.g., P2607081936)
            
        Returns:
            FactCard with wave info, or None if no wave found
        """
        # Try exact match first
        wave = self.waves_by_time.get(current_time_id)
        
        # If no exact match, find closest earlier wave
        if wave is None:
            sorted_times = sorted(self.waves_by_time.keys())
            idx = bisect.bisect_right(sorted_times, current_time_id) - 1
            if idx >= 0:
                wave = self.waves_by_time[sorted_times[idx]]
        
        if wave is None:
            return None
        
        wave_id = wave.get("wave_id", "UNKNOWN")
        pattern = wave.get("pattern", "UNKNOWN")
        members = wave.get("members", [])
        signature = wave.get("signature", "")
        color = wave.get("color", "GREEN")
        
        # Generate fact string
        member_count = len(members)
        if member_count >= 3:
            strength_desc = "Complex"
        elif member_count >= 2:
            strength_desc = "Developing"
        else:
            strength_desc = "Simple"
        
        level_type = "Bullish" if color == "GREEN" else "Bearish"
        fact = f"{strength_desc} {pattern} structure ({level_type}), {member_count} lines, signature: {signature[:30]}..."
        
        # Confidence based on member count
        confidence = min(member_count / 5.0, 0.9)
        
        # Get time_id from last member
        time_id = current_time_id
        if members:
            # Extract time from last line_id
            last_member = members[-1]
            # Line ID format: L2607081921-SUP-001
            if "-" in last_member:
                time_part = last_member[1:].split("-")[0]
                time_id = f"P{time_part}"
        
        return FactCard(
            source="WaveRAG",
            object_id=wave_id,
            fact=fact,
            confidence=round(confidence, 2),
            references=members,
            time_id=time_id
        )
    
    def get_all_facts(self) -> List[FactCard]:
        """
        Get FactCards for all lines and waves in the Truth Layer.
        """
        facts = []
        
        for line in self.lines:
            fact_card = self._create_line_fact_card(line, "LineRAG")
            facts.append(fact_card)
        
        for wave in self.waves:
            wave_id = wave.get("wave_id", "UNKNOWN")
            pattern = wave.get("pattern", "UNKNOWN")
            members = wave.get("members", [])
            color = wave.get("color", "GREEN")
            
            member_count = len(members)
            level_type = "Bullish" if color == "GREEN" else "Bearish"
            fact = f"{pattern} wave ({level_type}), {member_count} lines"
            confidence = min(member_count / 5.0, 0.9)
            
            time_id = "UNKNOWN"
            if members:
                last_member = members[-1]
                if "-" in last_member:
                    time_part = last_member[1:].split("-")[0]
                    time_id = f"P{time_part}"
            
            facts.append(FactCard(
                source="WaveRAG",
                object_id=wave_id,
                fact=fact,
                confidence=round(confidence, 2),
                references=members,
                time_id=time_id
            ))
        
        return facts
    
    def refresh(self) -> None:
        """
        Reload data from JSON files and rebuild indexes.
        Call this when Truth Layer is updated.
        """
        self._load_data()
        self._build_indexes()


# Convenience function for quick access
def create_rag(lines_path: str = "/workspace/truth_layer/storage/lines.json",
               waves_path: str = "/workspace/truth_layer/storage/waves.json") -> StructuralRAG:
    """
    Factory function to create a StructuralRAG instance.
    """
    return StructuralRAG(lines_path, waves_path)
